name: Bug
description: 反馈软件问题。
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        请尽量使用 https://codemutex.wiki/ns/ 上的**邮箱**反馈程序报错。因为后续的询问中可能包含软件日志。
        
        若无法填写下述询问，请优先到 [Discussions](https://github.com/codemutex/NextSSH-userland/discussions) 反馈。
        
  - type: textarea
    id: content
    attributes:
      label: 错误描述
      description: 请描述错误的现象或报错内容。
    validations:
      required: true
      
  - type: textarea
    id: reproduce
    attributes:
      label: 复现方法
      description: 请提供能重复此现象的方式。
    validations:
      required: true
      
  - type: textarea
    id: environment
    attributes:
      label: 环境
      value: |
        ### 本地
        
        - 操作系统/架构: 
        - 激活状态: 
        
        ### 主机
        
        - 操作系统/架构: 
        - 认证方式: 无/密码/私钥/交互式
    validations:
      required: true
