name: Feature request
description: 提出新的功能。
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        收到提交后不会做确认回复，在调查和排期期间 Issues 将保持开启。
        
        新功能提交后也可能会进一步询问具体细节，或预期的实现。

  - type: textarea
    id: content
    attributes:
      label: 描述预期的功能
    validations:
      required: true

  - type: textarea
    id: similar-function
    attributes:
      label: 在其他软件上是否存在类似的功能
      description: 可选，请提供连接和描述
    validations:
      required: false

  - type: textarea
    id: related-documentation
    attributes:
      label: 相关文档的链接
      description: 可选，与功能相关的云服务、软件的文档
    validations:
      required: false