name: Feature request
description: 提出新功能的需求。
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: checkboxes
    id: pre-check
    attributes:
      label: 预先检查
      # description: You may select more than one.
      options:
        - label: 此需求描述的是 SSH 客户端的功能，不是主机 Shell 或其他软件的功能。[无法确定……](https://github.com/codemutex/NextSSH-userland/discussions)
          required: true
  - type: textarea
    id: content
    attributes:
      label: 请大致描述需求
    validations:
      required: true
  - type: textarea
    id: similar-function
    attributes:
      label: 您是否在其他SSH客户端软件上使用过这个功能
      description: 可选，请提供连接和描述
    validations:
      required: false
  - type: textarea
    id: related-documentation
    attributes:
      label: 相关文档的链接
      description: 可选，与功能相关的云服务、软件的文档
    validations:
      required: false